export const apiGetAll = "Field/GetAll"
export const apiInsert = "Field/Insert"
export const apiUpdate = "Field/Update"
export const apiDelete = "Field/Delete"
export const apiGetCombobox = "Field/GetCombobox"
export const apiImportField = "Field/ImportField"
