export const apiGetListTags = "Tags/GetList"
export const apiInsertTags = "Tags/Insert"
export const apiUpdateTags = "Tags/Update"
export const apiDeleteTags = "Tags/Delete"
export const apiGetAllTags = "Tags/GetAllForCombobox"