export const apiGetAllUserDirectory = "Directory/GetAllUserDirectory"
export const apiInsertUserDirectory = "Directory/InsertUserDirectory"
export const apiUpdateUserDirectory = "Directory/UpdateUserDirectory"
export const apiDeleteUserDirectory = "Directory/DeleteUserDirectory"
export const apiBlockUserDirectory = "Directory/BlockUserDirectory"
export const apiResetPasswordByUserID = "Directory/ResetPasswordByUserID"
export const apiResetPassword = "User/ResetPassword"
